FROM rust:latest AS builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release -p server

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates wget \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /data
COPY --from=builder /usr/src/app/target/release/server /app/server
EXPOSE 8080
CMD ["./server"]
