{{- if .Values.rbac.read -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shellfleet-agent.fullname" . }}-read
  labels:
    {{- include "shellfleet-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "shellfleet-agent.fullname" . }}-read
subjects:
  - kind: ServiceAccount
    name: {{ include "shellfleet-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.rbac.exec }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shellfleet-agent.fullname" . }}-exec
  labels:
    {{- include "shellfleet-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "shellfleet-agent.fullname" . }}-exec
subjects:
  - kind: ServiceAccount
    name: {{ include "shellfleet-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.rbac.write }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shellfleet-agent.fullname" . }}-write
  labels:
    {{- include "shellfleet-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "shellfleet-agent.fullname" . }}-write
subjects:
  - kind: ServiceAccount
    name: {{ include "shellfleet-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
